version: '2'
services:
  orange: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: orange:v0.7.5
    ports:
    - 7777
    - 8888
    - 9999
    environment:
    - NGINX_DNS=8.8.8.8
    - NGINX_WORKER_PROCESSES=2
    - ORANGE_DB_HOST=192.168.31.213
    - ORANGE_DB_PORT=3306
    - ORANGE_DB_USER=root
    - ORANGE_DB_PWD=123
    - ORANGE_DB_NAME=orange